name: Zero-Downtime CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mevinumethdam
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mevinumethdam/gateease-api:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull Latest Image
        run: docker pull mevinumethdam/gateease-api:latest

      - name: Blue-Green Zero Downtime Deployment
        run: |
          ACTIVE_PORT=$(grep -oP 'server 127.0.0.1:\K\d+' /etc/nginx/sites-available/default)
          
          if [ "$ACTIVE_PORT" = "3000" ]; then
              NEW_PORT=3001
          else
              NEW_PORT=3000
          fi
          
          echo "Active Port: $ACTIVE_PORT | Deploying to New Port: $NEW_PORT"

          docker rm -f gateease-api-$NEW_PORT || true
          docker run -d --name gateease-api-$NEW_PORT -p $NEW_PORT:3000 mevinumethdam/gateease-api:latest

          sleep 10

          sudo sed -i "s/server 127.0.0.1:$ACTIVE_PORT/server 127.0.0.1:$NEW_PORT/" /etc/nginx/sites-available/default
          sudo systemctl reload nginx

          docker rm -f gateease-api-$ACTIVE_PORT || true
          docker rm -f gateease-api || true
          # Trigger pipeline (My 4th try)