name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Test Deployment Command
        run: |
          echo "Deploying to AWS EC2 Server..."
          echo "Current Path: $(pwd)"
          docker --version